HGconfigs:
  mushroom-density: 20
  damage-multiplier:
  soup-renegeration:
  Biomes:
    birch: true
    plains: true
    forest: true
    dark-forest: true

Commands:
  github:
    permission: false
    message: "https://github.com/sno0s"
