name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        working-directory: hardcoregames
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: hardcoregames
        run: ./gradlew build

      - name: Run tests
        working-directory: hardcoregames
        run: ./gradlew test

  upload:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission for Gradlew
        working-directory: hardcoregames
        run: chmod +x gradlew

      - name: Build
        working-directory: hardcoregames
        run: ./gradlew build

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hgplugin-jar
          path: hardcoregames/build/libs/*.jar
